<footer class="main-footer navbar-fixed-bottom  margin-bottom-none">
    <div class="pull-right hidden-xs small">
        <small><b>Version</b> 2.3.2</small>
    </div>

    <strong class="small">Usuario: </strong><a href="#"><?=$_SESSION['data_login']['nick_name']?> - <?=$_SESSION['data_home']['nombre_departamento']?></a>
    <!--    <strong>Copyright &copy; 2016-2017 <a href="http://prestamoexpress.com.mx" target="_blank">Prestamo Express</a>.</strong> All rights-->
<!--    reserved.-->
</footer>